version: "2"
services:
  web:
    container_name: web
    build: ./backend/
    restart: on-failure
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
  scrapper:
    container_name: scrapper
    build: ./scrapper/
    restart: on-failure
    command: python3 app.py
    ports:
      - "8080:8080"
